### ISSUE TITLE
Fehlermeldung beim Versionieren verbessern

### ISSUE THREAD

**Issue by ChristianHoesel** [bitctrl/de.bsvrz.sys.startstopp#11]
Wenn man in der Consolen GUI versioniert und keinen "Grund" angibt, dann gibt es nur die unverständliche Fehlermeldung: `de.bsvrz.sys.startstopp.api.client.StartStoppStatusException: Die aktuelle StartStopp-Konfiguration konnte nicht gesetzt werden`.

**Comment by upeuker** [comment]
Die Fehlermeldung enthält auch die Ursache für die Ablehnung der Versionierung.
