### ISSUE TITLE
Benachrichtigung bei Fehlern

### ISSUE THREAD

**Issue by ChristianHoesel** [bitctrl/de.bsvrz.sys.startstopp#3]
StartStopp könnte eine Benachrichtigung via EMail (oder anderer Kommunikationskanäle) an den Administrator versenden, z.B. wenn SWE's abstürtzen, sich ständig neu starten oder irgendwelche anderen Ausfallerscheinungen zeigen.
Das könnte man zwar auch mit Tools wie Nagios ermitteln, aber ich denke wir können hier auch typische Fehlverhalten für DAV SWE's ermitteln, die mit Nagios schwer zu erfassen sind. 
Außerdem wäre das ein viel niederschwelligerer Ansatz als die Einrichtung und Pflege eines Nagios.

**Comment by upeuker** [comment]
Da es um Probleme von den "normalen" SWE geht, d.h. eine Datenverteilerverbindung bestehen sollte, ergibt sich die Frage, ob das nicht über die Betriebsmeldungsverwaltung mit anschließendem KEX-Email-Fax-SMS gemacht werden sollte.

Den externe E-Mail-Versand "außen herum" würde ich (wenn überhaupt) maximal als Rückfallebene sehen.
