### ISSUE TITLE
Kontrolliertes Beenden via Shellskript

### ISSUE THREAD

**Issue by ChristianHoesel** [bitctrl/de.bsvrz.sys.startstopp#9]
In StartStopp 1 gab es die Möglichkeit des Beendens der Kernsoftware durch ausführen des Programms `de.bsvrz.sys.startstopp.befehle.BeendenBefehlsSender`.
Etwas ähnliches wird für das neue StartStopp auch benötigt werden um z.B. eine Integration ins systemd zu erleichtern.

**Comment by upeuker** [comment]
Neue Klasse de.bsvrz.sys.startstopp.console.StartStoppStopper zum Beenden von StartStopp per Kommandozeile.

siehe: https://gitlab.nerz-ev.de/ERZ/SWE_de.bsvrz.sys.startstopp/merge_requests/6
